DM-24318: Update fgcmcal with support for Gen3
lsst/fgcmcal pull request #44
Opened 2020-11-13 18:39 UTC by erykoff

This is a large overhaul of fgcmcal and the tests to work with gen3.

2021-01-12 19:34 UTC, natelust requested changes
Some comments to look at. There might be more, but I figured I would give these to you to address, and then look further with any changes that might be made

2021-01-12 19:34 UTC, natelust commented on python/lsst/fgcmcal/fgcmOutputProducts.py
> +    def _outputAtmospheres(self, butler, dataRefDict, atmCat, tract=None,
Similar to other output functinos

2021-01-12 19:34 UTC, natelust commented on python/lsst/fgcmcal/utilities.py
> +        datasetType = dataRef.ref.datasetType.name
You seem to be inconsistent in your files between this style check and isinstance checks.

2021-01-12 21:27 UTC, erykoff commented on python/lsst/fgcmcal/fgcmBuildStars.py
> +                               "be run with a butler and only supports Gen2.")
This is a funny one, I'm not sure what to do here.  This is a sanity check, but if it ever triggers it is 100% programmer error not user error.  I think I should rename this `_findAndGroupDataRefs` to make that clearer, even though it is called from `fgcmCalibrateTract`.

2021-01-12 21:32 UTC, erykoff commented on python/lsst/fgcmcal/fgcmBuildStars.py
> +                               "be run with a butler and only supports Gen2.")
I also changed the error to be hopefully clearer and more permissive:
```
        if butler is None:
            raise RuntimeError("Gen2 _findAndGroupDataRefs must be called with a butler.")
        if calexpDataRefDict is not None:
            self.log.warn("Ignoring calexpDataRefDict in gen2 _findAndGroupDataRefs")
```

2021-01-12 21:39 UTC, erykoff commented on python/lsst/fgcmcal/fgcmBuildStarsBase.py
> +        Gen3, use dataRefDict
I'm not sure what your question/comment is here.

2021-01-12 21:45 UTC, erykoff commented on python/lsst/fgcmcal/fgcmBuildStarsBase.py
> +           Dictionary of gen3 dataRefHandles for background info. FIXME
Absolutely, thanks for catching this.

2021-01-12 22:28 UTC, erykoff commented on python/lsst/fgcmcal/fgcmBuildStarsTable.py
> +            self.makeSubtask('fgcmLoadReferenceCatalog', refObjLoader=refObjLoader)
Oh, I didn't realize I could init the task and then set the `refObjLoader`.  That makes sense.

2021-01-12 22:51 UTC, erykoff commented on python/lsst/fgcmcal/fgcmFitCycle.py
> +            raise ValueError("cycleNumber must be of integer format")
Because this is the quickest way to check if something is an integer and allows negative numbers.  It's not pretty.

2021-01-12 23:04 UTC, natelust commented on python/lsst/fgcmcal/fgcmFitCycle.py
> +            raise ValueError("cycleNumber must be of integer format")
`if config.connections.cycleNumber.replace('-','').isdigit()`

2021-01-12 23:06 UTC, erykoff commented on python/lsst/fgcmcal/fgcmFitCycle.py
> +            raise ValueError("cycleNumber must be of integer format")
But then `5-3` would be legal.  It isn't.

2021-01-12 23:06 UTC, erykoff commented on python/lsst/fgcmcal/fgcmFitCycle.py
> +            raise ValueError("cycleNumber must be of integer format")
And I am _not_ pulling out `re`.

2021-01-12 23:06 UTC, natelust commented on python/lsst/fgcmcal/fgcmFitCycle.py
> +            raise ValueError("cycleNumber must be of integer format")
This would of course fail if we allowed something like "43-123"

2021-01-12 23:12 UTC, natelust commented on python/lsst/fgcmcal/fgcmFitCycle.py
> +            raise ValueError("cycleNumber must be of integer format")
maybe `if config.connections.cycleNumber.lstrip('-').isdigit()` then?

2021-01-12 23:43 UTC, erykoff commented on python/lsst/fgcmcal/fgcmBuildStarsTable.py
> +                    except KeyError:
I think the exceptions are rare, but yours is cleaner.

2021-01-12 23:45 UTC, erykoff commented on python/lsst/fgcmcal/fgcmCalibrateTractTable.py
> +        loaderName = config.fgcmBuildStars.fgcmLoadReferenceCatalog.refObjLoader.ref_dataset_name
I don't think so ... but maybe the ref_dataset_name config is no longer used in gen3, and so this can be deprecated at that point?

2021-01-12 23:58 UTC, erykoff commented on python/lsst/fgcmcal/fgcmCalibrateTractTable.py
> +            dataRefDict['fgcmPhotoCalibs'] = photoCalibRefDict
it's used in the output part of the task, but I might try refactoring as we discussed.

2021-01-13 17:26 UTC, natelust commented on tests/pipelines/fgcmMakeLutHsc.yaml
> +    class: lsst.fgcmcal.fgcmMakeLut.FgcmMakeLutTask
Also I should make note that if you dont have any other fields for the class you can just do:
```
fgcmMakeLut: lsst.fgcmcal.fgcmMakeLust.FgcmMakeLutTask
```

2021-01-14 17:51 UTC, erykoff commented on python/lsst/fgcmcal/fgcmBuildStarsTable.py
> +            self.makeSubtask('fgcmLoadReferenceCatalog', refObjLoader=refObjLoader)
Upon further testing, this is the only pattern that I could get to work for both gen2 and gen3 compatibility because gen2 needs the butler on init.

2021-01-14 17:52 UTC, erykoff commented on python/lsst/fgcmcal/fgcmCalibrateTractTable.py
> +        butlerQC.put(repeatabilityCat, outputRefs.fgcmRepeatability)
The other data products were put by the outputProducts part, but this is now more explicit.

2021-01-21 21:50 UTC, natelust approved these changes
A few random comments

2021-01-21 22:51 UTC, natelust commented on python/lsst/fgcmcal/fgcmBuildStarsTable.py
> +            lutDataRef = inputRefDict['fgcmLookUpTable']
I see it in line 297, I dont know how I missed it, perhaps outside the diff or something. Not sure, sorry for the noise.

2021-01-27 04:45 UTC, merged